---
include:
  - board: sofle_dongle
  - board: zitaotech_q10

  # Flash these once to clear saved Bluetooth/settings data.
  - board: sofle_dongle
    shield: settings_reset
  - board: zitaotech_q10
    shield: settings_reset
